# Generated by Django 3.1.4 on 2021-01-09 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateField(
                    blank=True, default=django.utils.timezone.now, verbose_name='date created')),
                ('rate', models.IntegerField(choices=[
                 (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('airport', models.ForeignKey(
                    default='', on_delete=django.db.models.deletion.CASCADE, to='airport.airport')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
            },
        ),
    ]
