# Generated by Django 3.1.4 on 2020-12-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Airport Name')),
                ('body', models.TextField(blank=True)),
                ('country', models.CharField(choices=[('Japan', 'Japan'), ('Korea', 'Korea'), ('Singapore', 'Singapore'), ('Australia', 'Australia'), ('Germany', 'Germany')], max_length=50, verbose_name='country')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('image1', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'verbose_name_plural': 'Airports',
                'db_table': 'airports',
            },
        ),
    ]
