# Generated by Django 3.1.4 on 2021-01-09 06:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Airport Name')),
                ('body', models.TextField(blank=True)),
                ('country', models.CharField(choices=[('japan', 'Japan'), ('korea', 'Korea'), ('singapore', 'Singapore'), ('australia', 'Australia'), ('germany', 'Germany')], max_length=50, verbose_name='country')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('image1', cloudinary.models.CloudinaryField(blank=True, default='v1610122704/media/noimage_r2hsre.png', max_length=255, null=True, verbose_name='Image 1')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, default='v1610122704/media/noimage_r2hsre.png', max_length=255, null=True, verbose_name='Image 2')),
                ('image3', cloudinary.models.CloudinaryField(blank=True, default='v1610122704/media/noimage_r2hsre.png', max_length=255, null=True, verbose_name='Image 3')),
                ('image4', cloudinary.models.CloudinaryField(blank=True, default='v1610122704/media/noimage_r2hsre.png', max_length=255, null=True, verbose_name='Image 4')),
                ('image5', cloudinary.models.CloudinaryField(blank=True, default='v1610122704/media/noimage_r2hsre.png', max_length=255, null=True, verbose_name='Image 5')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'verbose_name_plural': 'Airports',
                'db_table': 'airports',
            },
        ),
    ]
