# Generated by Django 3.1.4 on 2021-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_auto_20210320_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
