# Generated by Django 3.1.4 on 2021-03-20 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_auto_20210320_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
