# Generated by Django 3.1.4 on 2020-12-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image_path', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image_path2', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image_path3', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image_path4', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('image_path5', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
    ]
